### ISSUE TITLE
Hello 4chan

### ISSUE THREAD

**Issue by ghost** [facebookresearch/llama#123]
too many 4channers on here.

![download](https://user-images.githubusercontent.com/126925202/222951369-ae2099cb-4c43-4df1-9d4b-b90e4b860de0.jpg)

**Comment by Urammar** [comment]
Facebook AI research has been releasing models for years bro, you're acting like this is their first release.

AI is dangerous and open democratized access to it is widely accepted among researchers and industry leaders to be vital to avoiding honestly apocalyptic outcomes.

The sudden switch to financial interest in these models really only hit mainstream with ChatGPT, and "open ais" decision to be as closed as possible with it has been noted as very problematic.

One of these models, soon, is going to get really really smart, and if we arent sharing then we aren't learning how to make them safe.

The singularity isnt a question in the research community, its a timeline.

**Comment by Justin-Time-Coder** [comment]
Yes, but Meta released the model *after* the financial interest in these things. Which is why its confusing. Its the difference between Microsoft giving 10 billion for Chat GPT and Meta giving out its lesser models for free. Considering Metas current financial situation it seems like they would have been better off selling these models to Microsoft for a billion dollars.

**Comment by Urammar** [comment]
Its their mandate you brainlet, and secondly its worthless if the AI they make destroys the entire world because we released a paperclip maximizer.

If they actually do the thing and make AGI, money isn't going to matter.

**Comment by Justin-Time-Coder** [comment]
> Its their mandate you brainlet, and secondly its worthless if the AI they make destroys the entire world because we released a paperclip maximizer.
> 
> If they actually do the thing and make AGI, money isn't going to matter.
> 
> If thats a good or a bad thing, thats up to us today. But one way or the other, the future of humanity will no longer be in its own command.
> 
> So how about we get eyes on these things and work out how to make them work properly, and make that the good outcome, eh?

"brainlet" lol keep that on 4chan. I am imagining you right now: 😡😡😡Take a chill pill bruh. AI isn't about to destroy the world this year.

Some of us happen to be interested in business and it's workings. 🧐 I'm pretty sure the Big-Z-Man, is more interested in the 💰 than on the future of humanity. Well he should be because of all the money he's losing on VR at the moment.
