### ISSUE TITLE
FeedForward module's F.silu(self.w1(x)) * self.w3(x)?!

### ISSUE THREAD

**Issue by jxtps** [facebookresearch/llama#245]
[Reading the source code](https://github.com/facebookresearch/llama/blob/main/llama/model.py#L153) I couldn't help but notice that Llama uses a to me unusual formulation for the feed forward layer: 
```python
    def forward(self, x):
        return self.w2(F.silu(self.w1(x)) * self.w3(x))
```
The key part is `F.silu(self.w1(x)) * self.w3(x)`. After removing the python clutter it's basically: `silu(w1(x)) * w3(x)`, i.e. there's an element-wise multiplication between the output of `silu(w1(x))` and `w3(x)`. 

Where did this come from? There's no mention of it in either the [paper](https://arxiv.org/pdf/2302.13971v1.pdf) or the [blog post](https://ai.facebook.com/blog/large-language-model-llama-meta-ai/)? Thanks!

**Comment by unrealwill** [comment]
It looks like a gated network where silu is used instead of the more standard sigmoid

It may seems strange (as introducing quadratic terms may intuitively be harder to optimize numerically) to why it would work but it seems to improve performance.

2020 google paper "GLU Variants Improve Transformer" : https://arxiv.org/pdf/2002.05202.pdf
In the above paper, with experiences with T5, this feed forward architecture (denominated FFNSwiGLU in the paper) achieve the top performance (along FFNGEGLU)

**Comment by jxtps** [comment]
Interesting, thank you for the link! 

Do you also have any insight/suggestions on https://github.com/facebookresearch/llama/issues/246 ? Thanks!
