### ISSUE TITLE
test llama with GLUE

### ISSUE THREAD

**Issue by Molulu7** [facebookresearch/llama#27]
I open the llama programm in vs code and download the GLUE dataset mannually to the llama root. I try to train and test llama using SST-2 dataset, but this task is quite hard more than i expected.  I stuck in transferinng the SST-2 files into the files that llama accepted. Has anyone done the similar test?

**Comment by pauldog** [comment]
You won't be able to train it. It would take thousands of years on a desktop PC.

**Comment by chrisociepa** [comment]
@pauldog not necessary. It depends on the model size. If you create a model with ~40M params, you can train and run it locally without any sophisticated setup (6-8GB GPU could be good enough). But you are totally right if we are talking about models x B params.

**Comment by pauldog** [comment]
Interesting. I think I must have misunderstood and thought 7B was the minimum you must have. 

Will 40M be enough to get something interesting do you think?

**Comment by chrisociepa** [comment]
The model is just a container of weights, layers, etc. FB has created their own configurations and trained them, that's all. You can use the model, configure it with in your own way (number of heads, layers, embeddings, etc) and then train it. The tricky part here is to train it, because so far they have not provided any code to do that. I don't expect it to be a problem though and I think you could use similar approach as it was used for training other models (like GPT-2) since the architecture is pretty much the same here.

Re the model size - it is hard to answer your questions, because they are too generic. I think they are use cases where 40M is good enough (even much smaller models might be). With a single 8GB GPU, you could train it in a few days I think. But again, it depends on different factors (the training dataset size, parameters, even your implementation). I don't have trained my own LLAMA model at this moment, so nothing to public yet :)

**Comment by albertodepaola** [comment]
For future reference, check the current getting started guides on both [llama](https://github.com/facebookresearch/llama) and [llama-recipes](https://github.com/facebookresearch/llama-recipes) repositories
