### ISSUE TITLE
md5sum: WARNING: 156 of 156 computed checksums did NOT match

### ISSUE THREAD

**Issue by harishbattula** [facebookresearch/llama#602]
I'm trying to download LLAMA2 model into my local machine windows11, downloaded download.sh file from [here](https://raw.githubusercontent.com/facebookresearch/llama/main/download.sh) into my pwd. After running bash download.sh and entering mail in my cmd. tokenizer, tokenizer checklist, license and use_policies are downloaded and after that I'm getting this error.

**Comment by stevejohnston1** [comment]
Similar issue, after completing all the 70b model downloads, I was told that '4 computed checksums did NOT match'. Should I worry? (Checksums for 7b and 13b completed OK).
![image](https://github.com/facebookresearch/llama/assets/7082972/d351e3f7-3ce2-4cf6-ac20-da10fff8fce0)

**Comment by TCPhelps** [comment]
I also had "4 computed checksums did NOT match" - for the 70b-chat model.
<img width="295" alt="image" src="https://github.com/facebookresearch/llama/assets/5331804/7dbe80fb-8e60-459a-b9a0-ec8a02ef4bd4">

**Comment by hujohnson** [comment]
Same.  Downloading again but I assume the problem will not be fixed.

**Comment by stevejohnston1** [comment]
> Same. Downloading again but I assume the problem will not be fixed.

Hey @hujohnson did the second download deliver checksums that **_did_** match?

**Comment by hujohnson** [comment]
> > Same. Downloading again but I assume the problem will not be fixed.
> 
> Hey @hujohnson did the second download deliver checksums that **_did_** match?

@stevejohnston1 I requested another download link to a different email address and then did a fresh attempt, this time choosing "all" models.  And it worked.  Another change that may or may not be applicable is that I "caffeinated" my laptop with caffeinate -t <big number> so that it did not sleep during the download.  

Now my problem is that the instructions did not work on my M1 Mac with respect to the GPU.  I get 

RuntimeError: Distributed package doesn't have NCCL built in

And 

(my_tf_env) [hunter@metis llama]$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.25.2
Libc version: N/A

Python version: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:38:11)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] numpy                     1.23.2           py39h3668e8b_0    conda-forge
[conda] pytorch                   2.0.1                   py3.9_0    pytorch
[conda] torchaudio                2.0.2                  py39_cpu    pytorch
[conda] torchvision               0.15.2                 py39_cpu    pytorch

I barely know what this means, but I think the salient part is that I have no CUDA :)


Good luck!

**Comment by stevejohnston1** [comment]
> > Hey @hujohnson did the second download deliver checksums that **_did_** match?
> 
> @stevejohnston1 I requested another download link to a different email address and then did a fresh attempt, this time choosing "all" models. And it worked. Another change that may or may not be applicable is that I "caffeinated" my laptop with caffeinate -t so that it did not sleep during the download.
> 

Thanks for the update.

**Comment by samuelselvan** [comment]
Closing. Please let me know if anyone sees the same issue again.
