### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]  error

### ISSUE THREAD

**Issue by ryusangwon** [facebookresearch/llama#615]
Hi,
I'm trying to use Llama tokenizer
but I have trouble with this issue

RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 

My code is
<img width="715" alt="Screenshot 2023-08-03 at 6 09 34 PM" src="https://github.com/facebookresearch/llama/assets/78716763/c65a7341-a4c7-484d-a872-ca7ef2356c0f">

and error occurs in tokenizer.\

<img width="790" alt="Screenshot 2023-08-03 at 6 09 57 PM" src="https://github.com/facebookresearch/llama/assets/78716763/331cbad4-ad6d-413c-a48f-7b64634c6089">

<img width="788" alt="Screenshot 2023-08-03 at 6 10 20 PM" src="https://github.com/facebookresearch/llama/assets/78716763/d3011ef5-75a2-4d3c-bdee-52f55f3d880d">

How can I fix it?

**Comment by EmanuelaBoros** [comment]
If you wanna use the HuggingFace Llama tokenizer, you can load only [models](https://huggingface.co/meta-llama/Llama-2-7b-hf) available on HF.

If you wanna use the weights provided by Meta, you need to use the [tokenizer](https://github.com/facebookresearch/llama/blob/main/llama/tokenizer.py) from the repo.

**Comment by ryusangwon** [comment]
Hi
thanks for reply
I'm first beginner in AI.
I want to use Llama without huggingface.
How to use weights from Meta??
I wonder how to use that tokenizer.py file..

thanks

**Comment by EmanuelaBoros** [comment]
I see from your code that you already have the weights (in ./llama-2-7b/). I would recommend cloning the llama repository, check the Readme file and try to follow it.

**Comment by ryusangwon** [comment]
> 
Ok. I'll try! thanks a lot.

**Comment by ryusangwon** [comment]
> > 
> 
> Ok. I'll try! thanks a lot.

Now I can use Llama.
Thanks a lot.

**Comment by ryusangwon** [comment]
> I see from your code that you already have the weights (in ./llama-2-7b/). I would recommend cloning the llama repository, check the Readme file and try to follow it.

Now I can use Llama.
Thanks a lot.

**Comment by Titu97** [comment]
Hi everybody, I was having a lot of trouble running this. In case if you have been struggling with errors like "return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)", the real issue, as it turned out in my case, had to do with the  tokenizer.model file. What i did was to try to download the model  again, in a new directory. In the first few second, it downloaded a new set of tokenizer.model and  tokenizer_checklist.chk . Move these to the original directory. then running the following command worked for me 

torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir ./llama-2-7b/ \
    --tokenizer_path  ./tokenizer.model \
    --max_seq_len 128 --max_batch_size 4
