### ISSUE TITLE
What is llama2 trained on

### ISSUE THREAD

**Issue by annapras** [facebookresearch/llama#629]
Hello
Does llama2 provide a list of sources used for training the model.if so, where is that made available..

Is the complete code and training sources available in this github repo?

Thanks

**Comment by weizier** [comment]
I also want to get some infos about the pretrain dataset recipe.

**Comment by brianjking** [comment]
@annapras @weizier Read the paper, they just say "trust us, it's legit" - there is no dataset released.

Just the weights are open, data isn't.

**Comment by anubop** [comment]
From https://ai.meta.com/resources/models-and-libraries/llama/

> Llama 2 is pretrained using publicly available online data. An initial version of Llama Chat is then created through the use of supervised fine-tuning. Next, Llama Chat is iteratively refined using Reinforcement Learning from Human Feedback (RLHF), which includes rejection sampling and proximal policy optimization (PPO).

And from the paper:

> Our training corpus includes a new mix of data from publicly available sources, which does not include data
from Meta’s products or services. We made an effort to remove data from certain sites known to contain a
high volume of personal information about private individuals. We trained on 2 trillion tokens of data as this
provides a good performance–cost trade-off, up-sampling the most factual sources in an effort to increase
knowledge and dampen hallucinations.
We performed a variety of pretraining data investigations so that users can better understand the potential
capabilities and limitations of our models; results can be found in Section 4.1.
