### ISSUE TITLE
Request body format for chat models?

### ISSUE THREAD

**Issue by abhatia-07** [facebookresearch/llama#668]
Not sure if this is answered somewhere, what is the proper request body format for chat models like Llama 2 13B Chat.

The following body works for me, but I'm not sure why inputs is a list of lists.
Also keen to know what all parameters are available.

`{
	"inputs": [
		[
			{
				"role": "system",
				"content": "You are a helpful assistant"
			},
			{
				"role": "user",
				"content": "hi"
			}
		]
	],
	"parameters": {
		"max_new_tokens": 10
	}
}`

**Comment by WuhanMonkey** [comment]
Hey @abhatia-07, depends on which type of model you are using. Are you using the vanilla version of models or HuggingFace converted models? More information please.

**Comment by harishjayaram** [comment]
Thanks,
Harish

**Comment by abhatia-07** [comment]
Thanks for your reply, I'm using the `Llama2-13B-Chat` model, which we have deployed via AWS Jumpstart.

**Comment by WuhanMonkey** [comment]
It is a list of lists because you provide prompts and hyperparameter configurations in same inputs. For the prompts, you can provide system prompts as well as user prompts at the same time. If you are building a chat bot app, better to write a script to parse your input. We also have some example on llama recipe repo - https://github.com/facebookresearch/llama-recipes
