### ISSUE TITLE
Failed to run llama2-13B but it worked with llama2-7B

### ISSUE THREAD

**Issue by xros** [facebookresearch/llama#836]
It worked with llama2-7b. But when I tried to run the **llama2-13b** model using this `torchrun --nproc_per_node 2 example_chat_completion.py     --ckpt_dir /path/to/llama-2-13b-chat/     --tokenizer_path /path/to/tokenizer.model     --max_seq_len 128 --max_batch_size 4`, it didn't work.

Error log in brief: `RuntimeError: CUDA error: invalid device ordinal`

#### Full error log
```log
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
> initializing model parallel with size 2
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/home/alex/joy/ml/llama_playground/llama/example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/joy/ml/llama_playground/llama/example_chat_completion.py", line 35, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/home/alex/joy/ml/llama_playground/llama/llama/generation.py", line 92, in build
    torch.cuda.set_device(local_rank)
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 41031 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 41032) of binary: /home/alex/miniconda3/envs/llama/bin/python
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/llama/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/miniconda3/envs/llama/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-02_12:32:27
  host      : alex-workstation
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 41032)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(
```

#### System Specs
i9 9900K + 16G DDR4 (with 16GB swap) + 2080ti (modded version with 22GB VRAM, the card runs smoothly on Windows and Linux)
OS:
Ubuntu 22.04 x86_64
Environments:
From miniconda
```conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia```

#### My attempt NO.1 
I set the only GPU RTX 2080ti in the terminal. `export CUDA_VISIBLE_DEVICES=0`  **0** is the ID of my RTX 2080ti.
I looked up the GPU id by ```sudo lshw -C display```

Result.
```log
  *-display                 
       description: VGA compatible controller
       product: TU102 [GeForce RTX 2080 Ti Rev. A]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:186 memory:de000000-deffffff memory:2fe0000000-2fefffffff memory:2ff0000000-2ff1ffffff ioport:e000(size=128) memory:c0000-dffff
  *-display
       description: Display controller
       product: CoffeeLake-S GT2 [UHD Graphics 630]
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list
       configuration: driver=i915 latency=0
       resources: iomemory:2f0-2ef iomemory:2f0-2ef irq:185 memory:2ffe000000-2ffeffffff memory:2fd0000000-2fdfffffff ioport:f000(size=64)
  *-graphics
       product: EFI VGA
       physical id: 2
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=32 resolution=2560,1080
```
But it's still the same error. FYI, when starting to run llama2-13B, the ram usage hadn't even reached 16GB yet.

With some testing codes using pytorch
```python
import torch
device_count = torch.cuda.device_count()
print(f"Number of available devices: {device_count}")

for i in range(device_count):
    print(f"Device {i}: {torch.cuda.get_device_name(i)}")
```
output: 
**Number of available devices: 1
Device 0: NVIDIA GeForce RTX 2080 Ti**

Nvidia SMI info
```log
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:01:00.0  On |                  N/A |
| 41%   34C    P8              30W / 260W |    288MiB / 22528MiB |     12%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2216      G   /usr/lib/xorg/Xorg                          165MiB |
|    0   N/A  N/A      2338      G   /usr/bin/gnome-shell                         34MiB |
|    0   N/A  N/A     34805      G   ...26077060,3793940789578302769,262144       82MiB |
|    0   N/A  N/A     44004      G   ...sktop/5088/usr/bin/telegram-desktop        3MiB |
+---------------------------------------------------------------------------------------+
```

#### My attempt NO.2

Changed to Pytorch nightly and cuda 12.1 support. `conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch-nightly -c nvidia` My Linux is using Nvidia driver version 535.113.01 with cuda 12.2 support.

Pytorch version: 2.2.0.dev20231001
Same error.

#### My attempt NO.3
Downgrade the Linux driver? (Not tested yet)

#### My attempt NO.4
Use the Docker version Pytorch and CUDA inside a docker instance. https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch 

After downloading the docker image, i started a docker instance by doing so `docker run --gpus all -it --rm nvcr.io/nvidia/pytorch:23.09-py3`

Error
`docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]`

How to run llama2-13B-chat or 70B with a RTX graphics card of 22GB RAM? Thanks in advance!

**Comment by kiarash13p** [comment]
Want to approve your issue, same here!
also, I changed init_process_group from 'nccl' to 'gloo'

**Comment by HamidShojanazeri** [comment]
@xros seems you are running two processes for 13B where as you available device is 1?

**Comment by MahdiMohseni0033** [comment]
> @xros seems you are running two processes for 13B `torchrun --nproc_per_node 2` where as you available device is 1?

I tried with RTX 3090 , with `torchrun --nproc_per_node 1` for 13B-chat but faced with following Error :
 `
 (llama) (base) mmohseni@PC02--AI-LNX:/media/mmohseni/ubuntu/projects/llama$ torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-13b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "example_chat_completion.py", line 104, in <module>
    fire.Fire(main)
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example_chat_completion.py", line 35, in main
    generator = Llama.build(
  File "/media/mmohseni/ubuntu/projects/llama/llama/generation.py", line 103, in build
    assert model_parallel_size == len(
AssertionError: Loading a checkpoint for MP=2 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3564099) of binary: /media/mmohseni/ubuntu/enviroments/llama/bin/python
Traceback (most recent call last):
  File "/media/mmohseni/ubuntu/enviroments/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/media/mmohseni/ubuntu/enviroments/llama/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-18_16:53:46
  host      : PC02--AI-LNX
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3564099)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

 `
 I have no Idea how can I handle this one
