### ISSUE TITLE
It looks like your setup is missing fairscale. Also currently we only support NVIDIA GPUs, so maybe that might also be causing an issue.

### ISSUE THREAD

**Issue by Vatsal1106Virani** [facebookresearch/llama#893]
It looks like your setup is missing fairscale. Also currently we only support NVIDIA GPUs, so maybe that might also be causing an issue.

Closing this now, please reopen if you need to follow-up.

_Originally posted by @subramen in https://github.com/facebookresearch/llama/issues/881#issuecomment-1789324742_

**Comment by Vatsal1106Virani** [comment]
Which Version of NVIDIA GPU and CUDA version is required for this?

**Comment by subramen** [comment]
Try using CUDA 11.8 or 12.1 as that is what pytorch natively supports. 
We haven't tested on all Nvidia GPUs but A-series and many RTX series cards work well with Llama.

Pro tip: You can reply to a closed thread to reopen the conversation instead of starting a new one ;) Closing this thread for now
