### ISSUE TITLE
Might as well release the weights to all now...

### ISSUE THREAD

**Issue by ghost** [facebookresearch/llama#94]
In what will surprise no-one, the llama weights have already been leaked on torrent sites. I just did a search for it.

Therefore any bad-actors will already be able to access these weights.

So it makes no sense for Meta to gatekeep the weights any more. Since this just encourages people to download the weights from the torrents without even having to sign the Meta form.

Might as well make it free to everyone now. As now more "bad guys" will have the weights than the "good guys".

I wonder if Meta embedded secret code words inside the weights so it can tell who leaked them. 🤔 That's what I would do.

P.S. What is the law about copyright of neural network weights? I don't think it is copyrightable under US law so anyone can use them for commercial purposes.

**Comment by pauldog** [comment]
"leaked" 😂

**Comment by henk717** [comment]
I hope they will do this, our community finetunes models for fiction and we'd love to share finetunes with people. But we have no intent to do this illegally. Right now all the bad actors and our users can tune it, but we cant release anything ourselves because we have no rights to distribute the tunes.

If the model gets released publicly and we can release the result to our users it will be a net benefit for the open source community, while it has 0 negative impact now that all the bad actors already have it.

**Comment by jdwx** [comment]
> we cant release anything ourselves because we have no rights to distribute the tunes.

You could look at releasing adapters instead of finetunes. The performance is the same but you can distribute the adapter as an original work.  This would still require the end user to have the original weights (however they might obtain them) but it's a path for you to release as-is without violating the terms you agreed to in order to get the weights.

> If the model gets released publicly [...] it has 0 negative impact now that all the bad actors already have it.

This is unquestionably correct.

**Comment by henk717** [comment]
Lora is plan B but our tuners did not obtain the model officially yet. Its much easier for everyone if we can give the entire model though. Our software hasn't implemented Lora yet.

**Comment by albertodepaola** [comment]
For future reference, check both [llama](https://github.com/facebookresearch/llama) and [llama-recipes](https://github.com/facebookresearch/llama-recipes) repos for getting started guides.
