### ISSUE TITLE
Import Error Flash Attention during Training LlaMa-2

### ISSUE THREAD

**Issue by kandeldeepak46** [facebookresearch/llama#976]
## Describe the bug
 I am trying to fine-tune Llama-1 in RTX 6000 Ada...and I was able to validate the model but when I tried to run the fine tune the model I got the error as shown in the below image

```python


```

### Output
<img width="1794" alt="image" src="https://github.com/facebookresearch/llama/assets/33603333/18064405-3dc7-49a4-9cb1-fdda27c339f7">

## Runtime Environment
- Model: llama-2-7b-hf
- Using via huggingface?: yes
- OS: Linux/Ubuntu 22.04
- GPU VRAM: RTX 6000 Ada, 48GB
- Number of GPUs: 1
-  Nvidia

**Comment by subramen** [comment]
Your issue looks like it might be due to a faulty flash-attn install, maybe it's not the right platform? You might want to try reinstalling. Also since this is with the lit-gpt repo I'd recommend asking this over there. 

> Using via huggingface?: yes
AFAIK they don't use the models via huggingface, do you want to check how you're running it?

Closing this for now, feel free to reopen if needed
