### ISSUE TITLE
Does license allow dataset creation for small LMs?

### ISSUE THREAD

**Issue by nbroad1881** [facebookresearch/llama#998]
If I use llama 70b to create a dataset to train a small model like bert, does that violate the license.

This phrase is the most relevant:

> You will not use the Llama Materials or any output or results of the Llama Materials to improve any other large language model (excluding Llama 2 or derivative works thereof).

i am not a lawyer, but I would argue that bert is not a large language model.

**Comment by jspisak** [comment]
I'm sorry, we don't provide legal advice over GitHub. Please check your lawyer for legal guidance if you have questions on our license. Since you are a partner (HF) feel free to reach out through our BD team (Brandon Spence) or on Slack and we can discuss further if there is a specific project.

Sorry we couldn't help, at least here on HG..

**Comment by jspisak** [comment]
Closing to address offline if needed..
